config/routes.rb
Beacons::Application.routes.draw do
  devise_for :admins
  get '/' => "maps#index"
  resources :beacons
  resources :places
  resources :maps
  resources :uploads
  resources :map_actions
  resources :beacon_placements
  get "api/beacons"
  get "api/setup"
  get 'api/objects_for_map/:id' => 'api#objects_for_map'
  get 'api/beacons_on_map/:id' => 'api#beacons_on_map'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/beacon.rb
# encoding: utf-8 
class Beacon < ActiveRecord::Base 

  attr_accessible  :id, :uuid, :major, :minor, :color, :displayed_name

  validates :uuid, :presence => true
 	 
  def displayed_name
     "#{self.uuid}-#{self.major}-#{self.minor}"
  end
end

app/models/beacon_color.rb
class BeaconColor < ActiveRecord::Base
end

app/models/beacon_placement.rb
class BeaconPlacement < ActiveRecord::Base

	 attr_accessible  :id, :name, :x, :y, :beacon_id, :map_id, :action_id

end

app/models/map.rb
# encoding: utf-8 
class Map < ActiveRecord::Base 

  attr_accessible  :id, :name, :url, :floor, :width, :height, :place_id, :place_name, :image_height, :image_width, :map_type

  belongs_to :place 
  has_many :map_actions, dependent: :destroy 
  validates :name, :presence => true
  validates :width, :presence => true
  validates :height, :presence => true

  def place_name
     Place.find(self.place_id).name;
  end

end

app/models/map_action.rb
# encoding: utf-8 
class MapAction < ActiveRecord::Base 
  
  attr_accessible  :x, :y, :name, :proximity, :action_type, :content, :map_id, :media_url, :action_url, :beacon_id
  validates :name, :presence => true
end

app/models/place.rb
# encoding: utf-8 
class Place < ActiveRecord::Base 

  attr_accessible  :id, :name, :maps_count

  has_many :maps, dependent: :destroy 
  validates :name, :presence => true

  def maps_count
     Map.where(place_id: self.id).count;
  end
end

app/models/resource.rb
# encoding: utf-8 
class Resource < ActiveRecord::Base 

  attr_accessible  :id, :url, :type

  has_many :map_actions, dependent: :destroy 


end

app/models/upload.rb
class Upload < ActiveRecord::Base
  attr_accessible :upload
  has_attached_file :upload
  validates_attachment_content_type :upload, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "video/mp4", "audio/mp3"]

  include Rails.application.routes.url_helpers
  
  def to_jq_upload
    {
      "name" => read_attribute(:upload_file_name),
      "size" => read_attribute(:upload_file_size),
      "url" => upload.url(:original),
      "delete_url" => upload_path(self),
      "delete_type" => "DELETE" 
    }
  end

end

app/controllers/api_controller.rb
class ApiController < ApplicationController

	def beacons 
        render json: {"beacons" => Beacon.all}
	end

	def setup 
        render json: {"places" => Place.all,
        			  "maps" => Map.all}
	end

	def objects_for_map
		render json: {"beacons" => BeaconPlacement.find(:all, :conditions => { :map_id => params[:id]}),
					  "actions" => MapAction.find(:all, :conditions => { :map_id => params[:id]})}
	end

	def beacons_on_map 
		render json: {"beacons" => Beacon.find(BeaconPlacement.find(:all, :conditions => { :map_id => params[:id]}, :select => :beacon_id).map(&:beacon_id))}
	end
end

app/controllers/beacons_controller.rb
class BeaconsController  < InheritedResources::Base
  respond_to :html, :xml, :json
  skip_before_filter  :verify_authenticity_token
  
  def permitted_params
    params.permit(:beacon => [:uuid, :major, :minor, :color])
  end


  def index
  	@posts = Beacon.all
  end

  def new 
  	@beacon = Beacon.new
  end

  def edit 
    @beacon = Beacon.find(params[:id])
  end

end

app/controllers/maps_controller.rb
class MapsController < InheritedResources::Base
  respond_to :html, :xml, :json
  before_action :authenticate_admin!
 
  def permitted_params
    params.permit(:map => [:name, :url, :floor, :width, :height, :place_id, :image_width, :image_height, :map_type])
  end

  def index
  	@maps = Map.all
  end

  def new 
  	@map = Map.new
  end

  def edit 
    @map = Map.find(params[:id])
  end
end

app/controllers/places_controller.rb
class PlacesController  < InheritedResources::Base
  respond_to :html, :xml, :json
  before_action :authenticate_admin!

  def permitted_params
    params.permit(:place => [:name])
  end

  def index
  	@places = Place.all
  end

  def new 
  	@place = Place.new
  end

  def edit 
    @place = Place.find(params[:id])
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  # GET /uploads
  # GET /uploads.json

  def permitted_params
    params.permit(:upload => [:upload, :id])
  end

  def index
    @uploads = Upload.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uploads.map{|upload| upload.to_jq_upload } }
    end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
  end

  # POST /uploads
  # POST /uploads.json
  def create
    params.permit!
    @upload = Upload.new(params[:upload])

    respond_to do |format|
      if @upload.save
        format.html {
          render :json => [@upload.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json { render json: {files: [@upload.to_jq_upload]}, status: :created, location: @upload }
      else
        format.html { render action: "new" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.json
  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beacons_helper.rb
module BeaconsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/admin/dashboards/show.html.haml
- title t("admin.views.dashboard.title")

- content_for :pagepath do
  %li= link_to t("admin.views.dashboard.title"), [:admin, :projects]

app/views/admin/projects/_form.html.haml
= simple_nested_form_for [:admin, @project] do |f|
  = f.input :name, input_html: {class: "medium"}
  = f.input :kind, as: :select, collection: Project::PROJECT_KIND, input_html: {multiple: false, class: "medium chosen"}, allow_empty: false

  = f.button :submit, class: "btn"

app/views/admin/projects/_table.html.haml
- if collection.present?
  .shops_container
    %table.table.table-striped.table-bordered
      %thead
        %tr
          %th{style: "width:20%;"}= t("admin.views.projects.index.table.name")
          %th{style: "width:25%;"}= t("admin.views.projects.index.table.type")
          %th{style: "width:15%;"}
      %tbody
        - collection.each do |project|
          %tr
            %td= link_to project.name, [:admin, project]
            %td= project.kind_name
            %td.actions
              .pull-right
                = link_to [:edit, :admin, project], class: "btn btn-primary btn-mini" do
                  %i.iconsweets-create.iconsweets-white
                = link_to [:admin, project], class: "btn btn-danger btn-mini", confirm: t("admin.views.projects.index.delete_confirmation"), method: :delete do
                  %i.iconsweets-trashcan.iconsweets-white
- else
  = render "admin/common/empty"

app/views/admin/projects/edit.html.haml
- title t("admin.views.projects.edit.header")

- content_for :pagepath do
  %li= link_to t("admin.views.projects.index.header"), [:admin, :projects]
  %li= t("admin.views.projects.edit.header")
  
- content_for :pageheader do
  .pageheader
    .pageicon
      %span.icon-home
    .pagetitle
      %h5= t("admin.views.projects.index.header")
      %h1= t("admin.views.projects.edit.header")

%section.row-fluid
  = render "form"

app/views/admin/projects/index.html.haml
- title t("admin.views.projects.index.header")

- content_for :pagepath do
  %li= t("admin.views.projects.index.header")

- content_for :pageheader do
  .pageheader
    .pageicon
      %span.icon-home
    .pagetitle
      %h1= t("admin.views.projects.index.header")
      
%section
  .box
    %p.text-right
      = link_to t("admin.views.projects.index.add"), [:new, :admin, :project], class: "btn btn-primary"
    = render "table", locals: {collection: @collection}

app/views/admin/projects/new.html.haml
- title t("admin.views.projects.new.header")

- content_for :pagepath do
  %li
    = link_to t("admin.views.projects.index.header"), [:admin, :projects]
    %span.separator
  %li
    = t("admin.views.projects.new.header")

- content_for :pageheader do
  .pageheader
    .pageicon
      %span.icon-home
    .pagetitle
      %h5= t("admin.views.projects.index.header")
      %h1= t("admin.views.projects.new.header")
      
%section.row-fluid
  = render "form"

app/views/admin/projects/show.html.haml
- title @project.name

- content_for :pagepath do
  %li
    = link_to t("admin.views.projects.index.header"), [:admin, :projects]
    %span.separator
  %li
    = @project.name

- content_for :pageheader do
  .pageheader
    .pageicon
      %span.icon-file-alt
    .pagetitle
      %h5= t("admin.views.projects.index.header")
      %h1= @project.name
      
%section.row-fluid
  %h3
    = @project.name

app/views/admin/services/_form.html.haml
.service_form
  = simple_nested_form_for [:admin, @project, @service] do |f|
    = f.input :name, input_html: {class: "medium"}
    = f.input :_type, as: :select, collection: Service::SERVICE_KIND, input_html: {multiple: false, class: "medium chosen"},   allow_empty: false
    
    .service_form_custom_fields
      - unless @service.new_record?
        = render partial: "admin/services/partials/form/fields", locals: {fields: @service.class.form_fields, service: @service}
      
    = f.button :submit, class: "btn"  

app/views/admin/services/_table.html.haml
- unless collection.empty?
  .services_container
    %table.table.table-striped.table-bordered
      %thead
        %tr
          %th{style: "width:20%;"}= t("admin.views.services.index.table.name")
          %th{style: "width:20%;"}= t("admin.views.services.index.table.type")
          %th{style: "width:15%;"}
      %tbody
        - collection.each do |service|
          %tr
            %td= link_to service.name, admin_project_service_path(service, project_id: service.project_id)
            %td= service.service_kind_name
            %td.actions
              .pull-right
                = link_to edit_admin_project_service_path(service, project_id: service.project_id), class: "btn btn-primary btn-mini" do
                  %i.iconsweets-create.iconsweets-white
                = link_to admin_project_service_path(service, project_id: service.project_id), class: "btn btn-danger btn-mini", confirm: t("admin.views.services.index.delete_confirmation"), method: :delete do
                  %i.iconsweets-trashcan.iconsweets-white
- else
  = render "admin/common/empty"

app/views/admin/services/edit.html.haml
- title t("admin.views.services.edit.header")

- content_for :pagepath do
  %li
    = link_to @project.name, [:admin, @project]
    %span.separator
  %li
    = link_to t("admin.views.services.index.header"), [:admin, @project, :services]
    %span.separator
  %li
    = link_to @service.name, admin_project_service_path(@service, project_id: @service.project_id)
    %span.separator
  %li= t("admin.views.services.edit.header")
- content_for :pageheader do
  .pageheader
    .pageicon
      %span.icon-home
    .pagetitle
      %h5= t("admin.views.services.index.header")
      %h1= t("admin.views.services.edit.header")
      
%section.row-fluid
  = render "form"

app/views/admin/services/index.html.haml
- title t("admin.views.services.index.header")

- content_for :pagepath do
  %li
    = link_to @project.name, [:admin, @project]
    %span.separator
  %li= t("admin.views.services.index.header")

- content_for :pageheader do
  .pageheader
    .pageicon
      %span.icon-home
    .pagetitle
      %h1= t("admin.views.services.index.header")
      
%section
  .box
    %p.text-right
      = link_to t("admin.views.services.index.add"), [:new, :admin, @project, :service], class: "btn btn-primary"
    = render "table", locals: {collection: @collection}

app/views/admin/services/new.html.haml
- title t("admin.views.services.new.header")

- content_for :pagepath do
  %li
    = link_to @project.name, [:admin, @project]
    %span.separator
  %li
    = link_to t("admin.views.services.index.header"), [:admin, @project, :services]
    %span.separator
  %li= t("admin.views.services.new.header")
- content_for :pageheader do
  .pageheader
    .pageicon
      %span.icon-home
    .pagetitle
      %h5= t("admin.views.services.index.header")
      %h1= t("admin.views.services.new.header")
      
%section.row-fluid
  = render "form"

app/views/admin/services/partials/form/_fields.html.haml
- fields.keys.each do |key|
  = label_tag key, key
  - if fields[key] == :string
    = text_field_tag "service[#{key}]", (service.public_send(key) unless service.nil?)
  - elsif fields[key] == :text
    = text_area_tag "service[#{key}]", (service.public_send(key) unless service.nil?)
  - elsif fields[key] == :integer
    = number_field_tag "service[#{key}]", (service.public_send(key) unless service.nil?)

app/views/admin/services/partials/form/fields.js.erb
jQuery(".service_form_custom_fields").html('<%= escape_javascript render partial: "admin/services/partials/form/fields", locals: { fields: @fields, service: nil } %>');

app/views/admin/services/show.html.haml
- title @service.name

- content_for :pagepath do
  %li
    = link_to t("admin.views.projects.index.header"), [:admin, :projects]
    %span.separator
  %li
    = link_to t("admin.views.services.index.header"), [:admin, @project, :services]
    %span.separator
  %li
    = @service.name

- content_for :pageheader do
  .pageheader
    .pageicon
      %span.icon-file-alt
    .pagetitle
      %h5= t("admin.views.projects.index.header")
      %h1= @service.name
      
%section.row-fluid
  %h3
    = @service.name

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>